# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log_definition.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='log_definition.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x14log_definition.proto\"-\n\tint_field\x12\x10\n\x08int_reap\x18\x01 \x03(\x05\x12\x0e\n\x06holder\x18\x02 \x01(\x05\"3\n\x0cstring_field\x12\x10\n\x08str_reap\x18\x01 \x03(\t\x12\x11\n\tstr_count\x18\x02 \x03(\x05\"\x1f\n\nbool_field\x12\x11\n\tbool_reap\x18\x01 \x03(\x08\"1\n\x0b\x66loat_field\x12\x12\n\nfloat_reap\x18\x01 \x03(\x02\x12\x0e\n\x06holder\x18\x02 \x01(\x02\"L\n\x0bmatch_field\x12\x11\n\tmatch_str\x18\x01 \x02(\t\x12\x11\n\x05logic\x18\x02 \x01(\t:\x02or\x12\x17\n\x08negative\x18\x03 \x01(\x08:\x05\x66\x61lse\"\xf3\x03\n\x05\x66ield\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0f\n\x03pos\x18\x02 \x01(\x11:\x02-1\x12\x0c\n\x04type\x18\x03 \x02(\t\x12\x12\n\x03key\x18\x04 \x01(\x08:\x05\x66\x61lse\x12\x12\n\naggregated\x18\x05 \x01(\x08\x12\x13\n\x0b\x61ggregation\x18\x06 \x01(\t\x12\x12\n\nprocessing\x18\x07 \x01(\t\x12\x1a\n\x06int_fi\x18\x08 \x01(\x0b\x32\n.int_field\x12\x1d\n\x06str_fi\x18\t \x01(\x0b\x32\r.string_field\x12\x1c\n\x07\x62ool_fi\x18\n \x01(\x0b\x32\x0b.bool_field\x12\x1d\n\x07real_fi\x18\x0b \x01(\x0b\x32\x0c.float_field\x12\r\n\x05\x63ount\x18\x0c \x01(\r\x12\x15\n\rpreprocessing\x18\r \x01(\t\x12\x1d\n\x0b\x64\x61te_format\x18\x0e \x01(\t:\x08%m/%d/%Y\x12\x1c\n\x11processing_offset\x18\x0f \x01(\r:\x01\x31\x12\x0f\n\x07\x63reated\x18\x10 \x01(\x08\x12\x0e\n\x06\x66ilter\x18\x11 \x01(\t\x12\x13\n\x0b\x66ilter_type\x18\x12 \x01(\t\x12\x14\n\x0c\x66ilter_field\x18\x13 \x01(\t\x12(\n\nurl_format\x18\x14 \x01(\t:\x14%scheme://%host%port\x12\x1b\n\x05match\x18\x15 \x01(\x0b\x32\x0c.match_field\"~\n\x06logdef\x12\x13\n\x0b\x66ormat_name\x18\x01 \x02(\t\x12\x0e\n\x06\x64\x65lims\x18\x02 \x02(\t\x12\x16\n\x06\x66ields\x18\x03 \x03(\x0b\x32\x06.field\x12\x0f\n\x07\x61ppname\x18\x04 \x01(\t\x12\x11\n\tquotechar\x18\x05 \x01(\t\x12\x13\n\x0b\x63ommentchar\x18\x06 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_INT_FIELD = _descriptor.Descriptor(
  name='int_field',
  full_name='int_field',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='int_reap', full_name='int_field.int_reap', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='holder', full_name='int_field.holder', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=69,
)


_STRING_FIELD = _descriptor.Descriptor(
  name='string_field',
  full_name='string_field',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='str_reap', full_name='string_field.str_reap', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='str_count', full_name='string_field.str_count', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=122,
)


_BOOL_FIELD = _descriptor.Descriptor(
  name='bool_field',
  full_name='bool_field',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bool_reap', full_name='bool_field.bool_reap', index=0,
      number=1, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=155,
)


_FLOAT_FIELD = _descriptor.Descriptor(
  name='float_field',
  full_name='float_field',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='float_reap', full_name='float_field.float_reap', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='holder', full_name='float_field.holder', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=206,
)


_MATCH_FIELD = _descriptor.Descriptor(
  name='match_field',
  full_name='match_field',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='match_str', full_name='match_field.match_str', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='logic', full_name='match_field.logic', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("or").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='negative', full_name='match_field.negative', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=284,
)


_FIELD = _descriptor.Descriptor(
  name='field',
  full_name='field',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='field.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos', full_name='field.pos', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='field.type', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='key', full_name='field.key', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='aggregated', full_name='field.aggregated', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='aggregation', full_name='field.aggregation', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='processing', full_name='field.processing', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='int_fi', full_name='field.int_fi', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='str_fi', full_name='field.str_fi', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bool_fi', full_name='field.bool_fi', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='real_fi', full_name='field.real_fi', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='field.count', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='preprocessing', full_name='field.preprocessing', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='date_format', full_name='field.date_format', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("%m/%d/%Y").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='processing_offset', full_name='field.processing_offset', index=14,
      number=15, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='created', full_name='field.created', index=15,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='filter', full_name='field.filter', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='filter_type', full_name='field.filter_type', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='filter_field', full_name='field.filter_field', index=18,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='url_format', full_name='field.url_format', index=19,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("%scheme://%host%port").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='match', full_name='field.match', index=20,
      number=21, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=786,
)


_LOGDEF = _descriptor.Descriptor(
  name='logdef',
  full_name='logdef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='format_name', full_name='logdef.format_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='delims', full_name='logdef.delims', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fields', full_name='logdef.fields', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='appname', full_name='logdef.appname', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quotechar', full_name='logdef.quotechar', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='commentchar', full_name='logdef.commentchar', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=788,
  serialized_end=914,
)

_FIELD.fields_by_name['int_fi'].message_type = _INT_FIELD
_FIELD.fields_by_name['str_fi'].message_type = _STRING_FIELD
_FIELD.fields_by_name['bool_fi'].message_type = _BOOL_FIELD
_FIELD.fields_by_name['real_fi'].message_type = _FLOAT_FIELD
_FIELD.fields_by_name['match'].message_type = _MATCH_FIELD
_LOGDEF.fields_by_name['fields'].message_type = _FIELD
DESCRIPTOR.message_types_by_name['int_field'] = _INT_FIELD
DESCRIPTOR.message_types_by_name['string_field'] = _STRING_FIELD
DESCRIPTOR.message_types_by_name['bool_field'] = _BOOL_FIELD
DESCRIPTOR.message_types_by_name['float_field'] = _FLOAT_FIELD
DESCRIPTOR.message_types_by_name['match_field'] = _MATCH_FIELD
DESCRIPTOR.message_types_by_name['field'] = _FIELD
DESCRIPTOR.message_types_by_name['logdef'] = _LOGDEF

int_field = _reflection.GeneratedProtocolMessageType('int_field', (_message.Message,), dict(
  DESCRIPTOR = _INT_FIELD,
  __module__ = 'log_definition_pb2'
  # @@protoc_insertion_point(class_scope:int_field)
  ))
_sym_db.RegisterMessage(int_field)

string_field = _reflection.GeneratedProtocolMessageType('string_field', (_message.Message,), dict(
  DESCRIPTOR = _STRING_FIELD,
  __module__ = 'log_definition_pb2'
  # @@protoc_insertion_point(class_scope:string_field)
  ))
_sym_db.RegisterMessage(string_field)

bool_field = _reflection.GeneratedProtocolMessageType('bool_field', (_message.Message,), dict(
  DESCRIPTOR = _BOOL_FIELD,
  __module__ = 'log_definition_pb2'
  # @@protoc_insertion_point(class_scope:bool_field)
  ))
_sym_db.RegisterMessage(bool_field)

float_field = _reflection.GeneratedProtocolMessageType('float_field', (_message.Message,), dict(
  DESCRIPTOR = _FLOAT_FIELD,
  __module__ = 'log_definition_pb2'
  # @@protoc_insertion_point(class_scope:float_field)
  ))
_sym_db.RegisterMessage(float_field)

match_field = _reflection.GeneratedProtocolMessageType('match_field', (_message.Message,), dict(
  DESCRIPTOR = _MATCH_FIELD,
  __module__ = 'log_definition_pb2'
  # @@protoc_insertion_point(class_scope:match_field)
  ))
_sym_db.RegisterMessage(match_field)

field = _reflection.GeneratedProtocolMessageType('field', (_message.Message,), dict(
  DESCRIPTOR = _FIELD,
  __module__ = 'log_definition_pb2'
  # @@protoc_insertion_point(class_scope:field)
  ))
_sym_db.RegisterMessage(field)

logdef = _reflection.GeneratedProtocolMessageType('logdef', (_message.Message,), dict(
  DESCRIPTOR = _LOGDEF,
  __module__ = 'log_definition_pb2'
  # @@protoc_insertion_point(class_scope:logdef)
  ))
_sym_db.RegisterMessage(logdef)


# @@protoc_insertion_point(module_scope)
